---

- name: Make sure we have a 'wheel' group
  become: true
  group:
    name: wheel
    state: present
  tags: groups

- name: Allow 'wheel' group to have passwordless sudo
  become: true
  ansible.builtin.lineinfile:
    dest: /etc/sudoers.d/wheel
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'
  tags: groups
