---
collections:
  - name: ansible.posix

  - name: ansible.scm

  - name: ansible.utils

  # - name: https://github.com/redhat-cop/network.backup
  #   type: git

  # TO-DO: User's own collections can also be specified as mention below.
  # - name: my_organization.my_collection
  #   version: 1.2.3
  #   source: https://github.com/my_organization/my_collection.git

  - name: community.general

  - name: ondrejhome.ha_cluster # for my ha_cluster role
