---
- name: Install monit
  become: true
  ansible.builtin.ansible.builtin.apt:
    name:
      - monit
    state: present
    update_cache: true
  when: ansible_facts['distribution'] == 'Debian' or ansible_facts['distribution'] == 'Ubuntu'
  notify: restart monit
  tags: monit
