---
- name: Check if docker is running
  become: false
  ansible.builtin.command: systemctl is-active docker
  ignore_errors: true
  register: docker_state
  changed_when: false
  tags: iptables

- name: Fail if docker is active
  become: false
  ansible.builtin.fail:
    msg: "Docker is running. Stop it before changing iptables"
  when: docker_state.stdout == 'active'
  tags: iptables

- name: Disable ufw
  become: true
  ansible.builtin.systemd:
    name: ufw
    enabled: false
    state: stopped
  ignore_errors: true
  when: ansible_facts['distribution'] == 'Debian' or ansible_facts['distribution'] == 'Ubuntu'
  tags: iptables

- name: Install iptables persistent
  become: true
  ansible.builtin.apt:
    name: "iptables-persistent"
    state: present
  when: ansible_facts['distribution'] == 'Debian' or ansible_facts['distribution'] == 'Ubuntu'
  tags: iptables

- name: Install iptables persistent
  become: true
  ansible.builtin.dnf:
    name: "iptables-services"
    state: present
  when: ansible_facts['distribution'] == 'CentOS' or ansible_facts['distribution'] == 'RHEL'
  tags: iptables

- name: Start and endble iptables persistent
  become: true
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: restarted
    enabled: true
  loop: ["iptables"]
  tags: iptables

- name: Allow related and established connections
  become: true
  ansible.builtin.iptables:
    chain: INPUT
    ctstate: ESTABLISHED,RELATED
    jump: ACCEPT
    comment: Allow related and established
    rule_num: 1
  tags: iptables

- name: Allow localhost
  become: true
  ansible.builtin.iptables:
    chain: INPUT
    jump: ACCEPT
    in_interface: lo
    comment: Allow localhost
    rule_num: 2
  tags: iptables

- name: Allow new incoming SYN packets on TCP port 22 (SSH)
  become: true
  ansible.builtin.iptables:
    chain: INPUT
    destination_port: "22"
    protocol: tcp
    ctstate: NEW
    syn: match
    jump: ACCEPT
    comment: Accept new SSH connections
    rule_num: 3
  tags: iptables

- name: Allow any and all types of ICMP packets on the input chain
  become: true
  ansible.builtin.iptables:
    chain: INPUT
    protocol: icmp
    jump: ACCEPT
    rule_num: 4
  tags: iptables

- name: Allow monit
  become: true
  ansible.builtin.iptables:
    action: insert
    chain: INPUT
    jump: ACCEPT
    in_interface: "{{ ansible_facts['default_ipv4']['interface'] }}"
    protocol: tcp
    source: "0.0.0.0"
    destination_port: "2812"
    comment: monit
    rule_num: 5
  tags: iptables

- name: Reject any
  become: true
  ansible.builtin.iptables:
    chain: INPUT
    jump: REJECT
  tags: iptables

- name: Reject in forward
  become: true
  ansible.builtin.iptables:
    chain: FORWARD
    jump: REJECT
  tags: iptables

- name: Save current state of the firewall in system file
  become: true
  ansible.builtin.command: netfilter-persistent save
  notify: Restart iptables
  when: ansible_facts['distribution'] == 'Debian' or ansible_facts['distribution'] == 'Ubuntu'
  tags: iptables

- name: Save current state of the firewall in system file
  become: true
  ansible.builtin.command: service iptables save
  notify: Restart iptables
  when: ansible_facts['distribution'] == 'CentOS' or ansible_facts['distribution'] == 'RHEL'
  tags: iptables
