---
- name: Update apt-get repo and cache
  become: true
  ansible.builtin.apt:
    update_cache: "yes"
    cache_valid_time: "3600"
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  tags: timezone

- name: Install tzdata
  become: true
  ansible.builtin.apt:
    name:
      - tzdata
    state: present
    update_cache: true
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  tags: timezone

- name: Set timezone
  become: true
  community.general.timezone:
    name: "{{ timezone }}"
  tags: timezone
