---
- name: Get token on master
  ansible.builtin.command: kubeadm token create --print-join-command
  register: tokens
  when: (init.changed) and ("'master' in inventory_hostname")
  tags: kuber-deploy

- ansible.builtin.set_fact:
    token_command: "{{ tokens.stdout }}"
  when: "'master' in inventory_hostname"
  tags: kuber-deploy

- name: Register worker
  ansible.builtin.command: "{{ hostvars[groups['cluster-test-master'][0]]['token_command'] }}"
  when: "'worker' in inventory_hostname"
  tags: kuber-deploy
