---
# handlers restart iptables

- name: Restart iptables
  become: true
  ansible.builtin.systemd:
    name: iptables
    state: restarted
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
