---
- name: Reload firewalld
  become: true
  ansible.builtin.service:
    name: firewalld
    state: reloaded
  tags: ha_cluster

- name: Enable and start PCSD service
  become: true
  ansible.builtin.service:
    name: pcsd
    state: started
    enabled: true
  tags: ha_cluster

# Enable pacemaker and corosync for CentOS-7 or OEL-7
- name: Enable cluster services on all nodes for RHEL,OEL - 7,8,9
  become: true
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
    enabled: true
  with_items:
    - pacemaker
    - corosync
  when: ((ansible_facts['distribution'] == "CentOS" and ansible_facts['distribution_major_version'] == "7") or (ansible_facts['distribution'] == "OracleLinux"
    and ansible_facts['distribution_major_version'] == "7") or (ansible_facts['distribution'] == "CentOS" and ansible_facts['distribution_major_version'] ==
    "8") or (ansible_facts['distribution'] == "CentOS" and ansible_facts['distribution_major_version'] == "9"))
  tags: ha_cluster

# Enable only pacemaker for CentOS-6 or OEL-6
- name: Enable cluster services on all nodes for RHEL,OEL - 6
  become: true
  ansible.builtin.service:
    name: pacemaker
    state: started
    enabled: true
  when: ((ansible_facts['distribution'] == "CentOS" and ansible_facts['distribution_major_version'] == "6") or (ansible_facts['distribution'] == "OracleLinux"
    and ansible_facts['distribution_major_version'] == "6"))
  tags: ha_cluster
