---
- name: Copy nagios host cfg
  ansible.builtin.template:
    src: redis.j2
    dest: "{{ nagios_cfg_dest }}/{{ client_name }}/{{ inventory_hostname }}-redis-sentinel-cluster.cfg"
    owner: root
    mode: "0644"
  delegate_to: "{{ nagios_ost2_ip }}"
  tags:
    - nagios
    - nagios_redis_sentinel
    - nagios_server_redis_sentinel
