---
- name: Add PostgreSQL GPG apt Key
  become: true
  ansible.builtin.apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present
  when: ansible_facts['distribution'] == 'Debian' or ansible_facts['distribution'] == 'Ubuntu'
  tags: pg_client

- name: Add repository into sources list
  become: true
  ansible.builtin.apt_repository:
    repo: "deb http://apt.postgresql.org/pub/repos/apt {{ ansible_distribution_release }}-pgdg main"
    state: present
    filename: postgresql
  when: ansible_facts['distribution'] == 'Debian' or ansible_facts['distribution'] == 'Ubuntu'
  tags: pg_client

- name: Update apt-get repo and cache
  become: true
  ansible.builtin.apt:
    update_cache: "yes"
  when: ansible_facts['distribution'] == 'Debian' or ansible_facts['distribution'] == 'Ubuntu'
  tags: pg_client

- name: Install packages
  become: true
  ansible.builtin.apt:
    name: postgresql-client
    state: present
    update_cache: true
  when: ansible_facts['distribution'] == 'Debian' or ansible_facts['distribution'] == 'Ubuntu'
  tags: pg_client
