---
# tasks file for ipaclient

- name: Import variables specific to distribution
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "{{ role_path }}/vars/{{ ansible_facts['distribution'] }}-{{ ansible_facts['distribution_version'] }}.yml"
    - "{{ role_path }}/vars/{{ ansible_facts['distribution'] }}-{{ ansible_facts['distribution_major_version'] }}.yml"
    - "{{ role_path }}/vars/{{ ansible_facts['distribution'] }}.yml"
    - "{{ role_path }}/vars/default.yml"

  #- name: Import environment variable
  #  become: no
  #  include_vars:
  #   action: source ~/.bashrc
  #   delegate_to: localhost
  #set_fact: 
  #  ipaadmin_password: "{{ lookup('env','HOME') }}"

- name: Import environment variable
  become: false
  delegate_to: localhost
  ansible.builtin.set_fact:
    ipaadmin_password: "{{ lookup('env', 'IPAADMIN_PASSWORD') }}"

- name: Install IPA client
  ansible.builtin.include_tasks: tasks/install.yml
  when: state|default('present') == 'present'

- name: Uninstall IPA client
  ansible.builtin.include_tasks: tasks/uninstall.yml
  when: state|default('present') == 'absent'
