#!/bin/bash

# This script checks swap space activity on the machine it is run on. It outputs the 
# number of bytes moved from physical to swap space in the last DURATION seconds.
#
# Usage: "check_swap_activity -d DURATION(INTEGER) -w WARNING(INTEGER) -c CRITICAL(INTEGER)"
#
# WARNING < CRIT
#
# WARNING and CRIT are measured in bytes
#
# Returns the nagios native status codes:
#
# Nagios Status
#
# 0 = OK (SWAP usage below WARNING) 1 = WARNING (SWAP usage between
# WARNING AND CRITICAL) 2 = CRITICAL (SWAP usage higher than CRITICAL) 3
# = UNKNOWN (Wrong usage)
#
# Tested on:
# - Ubuntu 12.04
#
# Copyright 2012 Shu Wei Tan (webblazers@yahoo.com)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
# 
# Change History:
# 10/05/2012 - Version 1.0 - Shu Wei Tan (webblazers@yahoo.com)
#
## USAGE MESSAGE
usage() { 
cat << EOF
usage: $0 options

This script runs a swap space activity test on the machine.

OPTIONS:
   -h Show this message
   -d Duration in seconds to monitor for swap activity (not optional)
   -w Warning Level for Swap Out (not optional)
   -c Critical Level for Swap Out (not optional)
   -e Warning Level for Swap In (not optional)
   -v Critical Level for Swap In (not optional)

Warning Level should be lower than Critical Level!

EOF
}

SWAPI_WARN=
SWAPI_CRIT=
SWAPO_WARN=
SWAPO_CRIT=
## FETCH ARGUMENTS
while getopts "hd:w:c:e:v:" OPTION; do
        case "${OPTION}" in
                h)
                        usage
                        exit 3
                        ;;
                d)
                        DURATION=${OPTARG}
                        ;;
                w)
                        SWAPO_WARN=${OPTARG}
                        ;;
                c)
                        SWAPO_CRIT=${OPTARG}
                        ;;
                e)
                        SWAPI_WARN=${OPTARG}
                        ;;
                v)
                        SWAPI_CRIT=${OPTARG}
                        ;;
                ?)
                        usage
                        exit 3
                        ;;
        esac
done


## CHECK ARGUMENTS
if [ -z ${DURATION} ] ||  [ -z ${SWAPI_WARN} ] || [ -z ${SWAPI_CRIT} ] || [ -z ${SWAPO_WARN} ] || [ -z ${SWAPO_CRIT} ] || [ ${SWAPI_WARN} -gt ${SWAPI_CRIT} ] || [ ${SWAPO_WARN} -gt ${SWAPO_CRIT} ] ; then
        usage
        exit 3
fi

## GET SWAP INFO FROM MACHINE
SWAPOUT_ACTIVITY=$(vmstat ${DURATION} 2 | tail -n 1 | awk '{print $8}')
SWAPIN_ACTIVITY=$(vmstat ${DURATION} 2 | tail -n 1 | awk '{print $7}')


## CHECK SWAPPING ON MACHINE
if [[ ${SWAPIN_ACTIVITY} -lt ${SWAPI_WARN}  &&  ${SWAPOUT_ACTIVITY} -lt ${SWAPO_WARN} ]]; then
	## SWAPIO IS OK
        LINE1="OK! Swapin in last ${DURATION} second(s): ${SWAPIN_ACTIVITY} | swapin=${SWAPIN_ACTIVITY}P/s;${SWAPI_WARN};${SWAPI_CRIT};"
        LINE2="OK! Swapout in last ${DURATION} second(s): ${SWAPOUT_ACTIVITY} | swapout=${SWAPOUT_ACTIVITY}P/s;${SWAPO_WARN};${SWAPO_CRIT};"
        echo $LINE2
        echo $LINE1
	exit 0
elif [[ ${SWAPIN_ACTIVITY} -ge ${SWAPI_WARN}  &&  ${SWAPIN_ACTIVITY} -lt ${SWAPI_CRIT}  &&  ${SWAPOUT_ACTIVITY} -lt ${SWAPO_WARN} ]] ; then
	## SWAPIN WARNING
	## SWAPOUT OK
        LINE1="WARNING! Swapin in last ${DURATION} second(s): ${SWAPIN_ACTIVITY} | swapin=${SWAPIN_ACTIVITY}P/s;${SWAPI_WARN};${SWAPI_CRIT};"
        LINE2="OK! Swapout in last ${DURATION} second(s): ${SWAPOUT_ACTIVITY} | swapout=${SWAPOUT_ACTIVITY}P/s;${SWAPO_WARN};${SWAPO_CRIT};"
        echo $LINE1
        echo $LINE2
	exit 1
elif [[ ${SWAPIN_ACTIVITY} -ge ${SWAPI_WARN} && ${SWAPIN_ACTIVITY} -lt ${SWAPI_CRIT} && ${SWAPOUT_ACTIVITY} -ge ${SWAPO_WARN} && ${SWAPOUT_ACTIVITY} -lt ${SWAPO_CRIT} ]] ; then
    ## SWAPIN  WARNING
    ## SWAPOUT WARNING
        LINE3="WARNING! SWAPIN & SWAPOUT are in warning state!"
        LINE2="WARNING! Swapout in last ${DURATION} second(s): ${SWAPOUT_ACTIVITY} | swapout=${SWAPOUT_ACTIVITY}P/s;${SWAPO_WARN};${SWAPO_CRIT};"
        LINE1="WARNING! Swapin in last ${DURATION} second(s): ${SWAPIN_ACTIVITY} | swapin=${SWAPIN_ACTIVITY}P/s;${SWAPI_WARN};${SWAPI_CRIT};"
        echo $LINE3
        echo $LINE2
        echo $LINE1
    exit 1
elif [[ ${SWAPIN_ACTIVITY} -ge ${SWAPI_WARN} && ${SWAPIN_ACTIVITY} -lt ${SWAPI_CRIT} && ${SWAPOUT_ACTIVITY} -ge ${SWAPO_CRIT} ]] ; then
    ## SWAPIN WARNING
    ## SWAPOUT CRIT
        LINE2="CRITICAL! Swapout in last ${DURATION} second(s): ${SWAPOUT_ACTIVITY} | swapout=${SWAPOUT_ACTIVITY}P/s;${SWAPO_WARN};${SWAPO_CRIT};"
        LINE1="WARNING! Swapin in last ${DURATION} second(s): ${SWAPIN_ACTIVITY} | swapin=${SWAPIN_ACTIVITY}P/s;${SWAPI_WARN};${SWAPI_CRIT};"
        echo $LINE2
        echo $LINE1
    exit 2
elif [[ ${SWAPIN_ACTIVITY} -ge ${SWAPI_CRIT} && ${SWAPOUT_ACTIVITY} -ge ${SWAPO_WARN} && ${SWAPOUT_ACTIVITY} -lt ${SWAPO_CRIT}  ]] ; then
    ## SWAPIN CRIT
    ## SWAPOUT WARNING
        LINE2="WARNING! Swapout in last ${DURATION} second(s): ${SWAPOUT_ACTIVITY} | swapout=${SWAPOUT_ACTIVITY}P/s;${SWAPO_WARN};${SWAPO_CRIT};"
        LINE1="CRITICAL! Swapin in last ${DURATION} second(s): ${SWAPIN_ACTIVITY} | swapin=${SWAPIN_ACTIVITY}P/s;${SWAPI_WARN};${SWAPI_CRIT};"
        echo $LINE1
        echo $LINE2
    exit 2
elif [[ ${SWAPIN_ACTIVITY} -ge ${SWAPI_CRIT} && ${SWAPOUT_ACTIVITY} -ge  ${SWAPO_CRIT}  ]] ; then
    ## SWAPIN CRIT
    ## SWAPOUT CRIT
        LINE2="CRITICAL! Swapout in last ${DURATION} second(s): ${SWAPOUT_ACTIVITY} | swapout=${SWAPOUT_ACTIVITY}P/s;${SWAPO_WARN};${SWAPO_CRIT};"
        LINE1="CRITICAL! Swapin in last ${DURATION} second(s): ${SWAPIN_ACTIVITY} | swapin=${SWAPIN_ACTIVITY}P/s;${SWAPI_WARN};${SWAPI_CRIT};"
        echo $LINE2
        echo $LINE1
    exit 2
elif [[ ${SWAPIN_ACTIVITY} -ge ${SWAPI_CRIT} &&  ${SWAPOUT_ACTIVITY} -lt ${SWAPO_WARN} ]] ; then
	## SWAPIN CRIT
	## SWAPOUT OK
        LINE1="CRITICAL! Swapin in last ${DURATION} second(s): ${SWAPIN_ACTIVITY} | swapin=${SWAPIN_ACTIVITY}P/s;${SWAPI_WARN};${SWAPI_CRIT};"
        LINE2="OK! Swapout in last ${DURATION} second(s): ${SWAPOUT_ACTIVITY} | swapout=${SWAPOUT_ACTIVITY}P/s;${SWAPO_WARN};${SWAPO_CRIT};"
        echo $LINE1
        echo $LINE2
	exit 2
elif [[ ${SWAPOUT_ACTIVITY} -ge ${SWAPO_WARN}  && ${SWAPOUT_ACTIVITY} -lt ${SWAPO_CRIT} && ${SWAPIN_ACTIVITY} -lt ${SWAPI_WARN} ]] ; then
    ## SWAPIN OK
    ## SWAPOUT WARNING
        LINE1="WARNING! Swapout in last ${DURATION} second(s): ${SWAPOUT_ACTIVITY} | swapout=${SWAPOUT_ACTIVITY}P/s;${SWAPO_WARN};${SWAPO_CRIT};"
        LINE2="OK! Swapin in last ${DURATION} second(s): ${SWAPIN_ACTIVITY} | swapin=${SWAPIN_ACTIVITY}P/s;${SWAPI_WARN};${SWAPI_CRIT};"
        echo $LINE1
        echo $LINE2
    exit 1	
elif [[ ${SWAPOUT_ACTIVITY} -ge ${SWAPO_CRIT} && ${SWAPIN_ACTIVITY} -lt ${SWAPI_WARN} ]] ; then
    ## SWAPIN OK
    ## SWAPOUT CRIT
        LINE1="CRITICAL! Swapout in last ${DURATION} second(s): ${SWAPOUT_ACTIVITY} | swapout=${SWAPOUT_ACTIVITY}P/s;${SWAPO_WARN};${SWAPO_CRIT};"
        LINE2="OK! Swapin in last ${DURATION} second(s): ${SWAPIN_ACTIVITY} | swapin=${SWAPIN_ACTIVITY}P/s;${SWAPI_WARN};${SWAPI_CRIT};"
        echo $LINE1
        echo $LINE2
    exit 2
else

	## SHOULD NEVER REACH THIS POINT, MUST BE USAGE :)
        usage
        exit 3
fi
