---
# defaults file for ipaclient

ipaclient_force_join: false
ipaclient_ntp: false
ipaclient_mkhomedir: true
ipaclient_kinit_attempts: 5
ipaclient_use_otp: false
ipaclient_allow_repair: false
ipaclient_on_master: false
ipaclient_no_ntp: false
ipaclient_no_dns_lookup: false
ipaclient_ssh_trust_dns: false
