---
- name: Update apt-get repo and cache
  become: true
  ansible.builtin.apt:
    update_cache: "yes"
    cache_valid_time: "3600"
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  tags: packages

- name: Install packages
  become: true
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop: "{{ packages }}"
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  tags: packages
