---
- name: Create git folder in home
  ansible.builtin.file:
    path: ~/git/{{ PROJECT_NAME }}
    state: directory
    mode: "0764"
  tags: jforwarder

- name: Git clone repo
  ansible.builtin.git:
    clone: true
    repo: "{{ GIT_REPO_URL }}"
    dest: ~/git/{{ PROJECT_NAME }}
  ignore_errors: true
  tags: jforwarder

- name: Git pull repo
  ansible.builtin.git:
    clone: false
    repo: "{{ GIT_REPO_URL }}"
    dest: ~/git/{{ PROJECT_NAME }}
  ignore_errors: true
  tags: jforwarder

- name: Copy env file for project
  ansible.builtin.ansible.builtin.template:
    src: project_env.j2
    dest: ~/git/{{ PROJECT_NAME }}/.env
    mode: "0440"
  tags: jforwarder

- name: Copy env file for monitoring
  ansible.builtin.ansible.builtin.template:
    src: monitoring_env.j2
    dest: ~/git/{{ PROJECT_NAME }}/monitoring/.env
    mode: "0440"
  tags: jforwarder

- name: Copy pgpass to home dir
  ansible.builtin.ansible.builtin.template:
    src: pgpass.j2
    dest: ~/.pgpass
    mode: "0600"
  tags: jforwarder

- name: Create backup folder for subscriptions-holder-db
  ansible.builtin.file:
    path: ~/backups/{{ PROJECT_NAME }}/db
    state: directory
    mode: "0764"
  tags: jforwarder

- name: Create backup folder for telegram-chat-service-db
  ansible.builtin.file:
    path: ~/backups/{{ PROJECT_NAME }}/telegram-chat-service
    state: directory
    mode: "0764"
  tags: jforwarder

- name: Copy backup script subscriptions-holder-db
  ansible.builtin.ansible.builtin.template:
    src: backup-subscriptions-holder-db-in-kuber.j2
    dest: ~/backups/{{ PROJECT_NAME }}/backup-subscriptions-holder-db-in-kuber.sh
    mode: "0764"
  tags: jforwarder

- name: Add backup to cron subscriptions-holder-db
  ansible.builtin.cron:
    name: "backup db"
    minute: "0"
    hour: "1"
    job: "sh ~/backups/{{ PROJECT_NAME }}/backup-subscriptions-holder-db-in-kuber.sh"
    state: present
  tags: jforwarder

- name: Copy backup script backup-telegram-chat-db
  ansible.builtin.ansible.builtin.template:
    src: backup-telegram-chat-db-in-kuber.j2
    dest: ~/backups/{{ PROJECT_NAME }}/backup-telegram-chat-db-in-kuber.sh
    mode: "0764"
  tags: jforwarder

- name: Add backup to cron backup-telegram-chat-db
  ansible.builtin.cron:
    name: "backup telegram-chat-service-db"
    minute: "0"
    hour: "1"
    job: "sh ~/backups/{{ PROJECT_NAME }}/backup-telegram-chat-db-in-kuber.sh"
    state: present
  tags: jforwarder

- name: Add zipkin deps hourly to cron
  ansible.builtin.cron:
    name: "zipkin hourly"
    minute: "0"
    job: "docker exec --user root zipkin-dependencies /bin/sh /etc/periodic/hourly/zipkin-dependencies-today"
    state: present
  tags: jforwarder

- name: Add backup to cron
  ansible.builtin.cron:
    name: "zipkin daily"
    minute: "0"
    hour: "2"
    job: "docker exec --user root zipkin-dependencies /bin/sh /etc/periodic/daily/zipkin-dependencies-yesterday"
    state: present
  tags: jforwarder
