---
- name: Set includedir in sudoers
  become: true
  ansible.builtin.lineinfile:
    dest: /etc/sudoers
    line: "#includedir /etc/sudoers.d"
    state: present
    validate: "/usr/sbin/visudo -cf %s"
  tags: sudoers

- name: Create sudoers.d dir
  become: true
  ansible.builtin.file:
    path: /etc/sudoers.d
    state: directory
    mode: "0750"
    owner: root
    group: root
  tags: sudoers

- name: Accept WHEEL group for SUDO without password
  become: true
  ansible.builtin.template:
    src: sudoers.d/wheel.j2
    dest: "/etc/sudoers.d/{{ item }} "
    owner: root
    group: root
    mode: "0440"
    backup: "no"
  notify: wheel permissions
  with_items: "{{ sudoers }}"
  tags: sudoers
