---
- name: System details
  ansible.builtin.debug:
    msg: "{{ item }}"
  with_items:
    - "{{ ansible_facts['distribution'] }}"
    - "{{ ansible_facts['architecture'] }}"
    - "{{ ansible_facts['distribution_version'] }}"
    - "{{ ansible_facts['distribution_release'] }}"
    - "{{ ansible_facts['distribution_major_version'] }}"
  tags: docker

- name: Debug message
  ansible.builtin.debug:
    msg: "{{ [ansible_facts['architecture']] | map('extract', deb_architectures) | first }}"
  tags: docker

- name: Include for debian/Ubuntu
  ansible.builtin.include_tasks: "deb.yml"
  when: ansible_facts['distribution'] == 'Debian' or ansible_facts['distribution'] == 'Ubuntu'

- name: Include for CentOS/RHEL
  ansible.builtin.include_tasks: "rhel.yml"
  when: ansible_facts['distribution'] == 'CentOS' or ansible_facts['distribution'] == 'RHEL'

- name: Setup docker user
  become: true
  ansible.builtin.user:
    name: "{{ item.user }}"
    append: true
    groups: docker
    uid: "{{ item.uid }}"
    state: "{{ item.state }}"
    comment: "{{ item.comment }}"
    shell: "{{ item.shell }}"
  with_items: "{{ users }}"
  when: item.state == "present"
  ignore_errors: true
  tags: docker

#- name: Create Docker-Compose symlink
#  ansible.builtin.command:
#    cmd: ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
#    creates: /usr/bin/docker-compose
#  tags: docker

#- name: Add private registry
#  ansible.builtin.template:
#    src: daemon.j2
#    dest: /etc/docker/daemon.json
#    mode: preserve
#  notify: restart docker
#  tags: docker
