---

- name: Copy nagios host cfg
  ansible.builtin.template:
    src: cluster-res.j2
    dest: "{{ nagios_cfg_dest }}/{{ client_name }}/{{ inventory_hostname }}-cluster-res.cfg"
    owner: root
    mode: "0644"
  delegate_to: "{{ nagios_ost2_ip }}"
  tags:
    - nagios
    - nagios_cluster_res
    - nagios_server_cluster_res
