---
- name: Add repository into sources list
  become: true
  ansible.builtin.apt_repository:
    repo: "deb https://ppa.launchpadcontent.net/liujianfeng1994/panfork-mesa/ubuntu/ {{ ansible_distribution_release }} main"
    state: present
    filename: panfork-mesa
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  tags: armbian_3d_acceleration

- name: Add repository into sources list
  become: true
  ansible.builtin.apt_repository:
    repo: "deb https://ppa.launchpadcontent.net/liujianfeng1994/rockchip-multimedia/ubuntu/ {{ ansible_distribution_release }} main"
    state: present
    filename: rockchip-multimedia
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  tags: armbian_3d_acceleration

- name: Install packages
  become: true
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  loop: ["mali-g610-firmware", "rockchip-multimedia-config"]
  tags: armbian_3d_acceleration
