---
- name: Collectd | Install disk plugin
  ansible.builtin.dnf:
    name: collectd-disk
    state: present
  when: (ansible_facts['distribution'] == "CentOS" and ansible_facts['distribution_major_version'] == "6" and "disk" in default_plugins) or (ansible_facts['distribution'] == "RedHat" and
    ansible_facts['distribution_major_version'] == "6" and "disk" in default_plugins)
  tags: collectd

- name: Collectd | Install mysql plugin
  ansible.builtin.dnf:
    name: collectd-mysql
    state: present
  when: ("mysql" in collectd_extra_plugins)
  tags: collectd

- name: Collectd | Install memcache plugin
  ansible.builtin.dnf:
    name: collectd-memcachec
    state: present
  when: ("memcache" in collectd_extra_plugins)
  tags: collectd

- name: Collectd | Install varnish plugin
  ansible.builtin.dnf:
    name: collectd-varnish
    state: present
  when: ("varnish" in collectd_extra_plugins)
  tags: collectd

- name: Collectd | Install nginx plugin
  ansible.builtin.dnf:
    name: collectd-nginx
    state: present
  when: ("nginx" in collectd_extra_plugins)
  tags: collectd

- name: Collectd | Install apache plugin
  ansible.builtin.dnf:
    name: collectd-apache
    state: present
  when: ("apache_status" in collectd_extra_plugins)
  tags: collectd

- name: Collectd | Install redis plugin
  ansible.builtin.dnf:
    name: collectd-redis
    state: present
  when: ("redis" in collectd_extra_plugins)
  tags: collectd

- name: Collectd | Install postgresql plugin
  ansible.builtin.dnf:
    name: collectd-postgresql
    state: present
  when: ("postgresql" in collectd_extra_plugins)
  tags: collectd
