---
- name: Collectd | Install collectd package
  ansible.builtin.dnf:
    name: collectd
    state: present
  tags: collectd

- name: Collectd | Enable collectd service
  ansible.builtin.service:
    name: collectd
    state: started
    enabled: "yes"
  tags: collectd

- name: Collectd | Write main config file
  ansible.builtin.template:
    src: collectd.conf.j2
    dest: /etc/collectd.conf
    owner: root
    group: root
    mode: "0644"
  notify: restart collectd
  tags: collectd

- name: Collectd | Rsyslog configure.
  ansible.builtin.copy:
    src: collectd.conf
    dest: /etc/rsyslog.d/collectd.conf
    mode: "0644"
  notify: Restart rsyslog
  tags: collectd

- name: Collectd | Logrotate configure
  ansible.builtin.template:
    src: collectd.logrotate.j2
    dest: /etc/logrotate.d/collectd
    owner: root
    group: root
    mode: "0644"
  tags: collectd

- name: Collectd | Create config plugins /etc/collectd.d
  ansible.builtin.file:
    name: "{{ collectd_etc_plugins }}"
    state: directory
    owner: root
    group: root
    mode: "0755"
  tags: collectd
