---
- name: Collectd main
  ansible.builtin.include_tasks: "collectd_main.yml"
  when: (ansible_facts['distribution'] == "CentOS" and ansible_facts['distribution_major_version'] == "6") or (ansible_facts['distribution'] == "RedHat" and
    ansible_facts['distribution_major_version'] == "6") or (ansible_facts['distribution'] == "OracleLinux" and ansible_facts['distribution_major_version'] ==
    "6")
  tags: collectd

- name: Collectd 7
  ansible.builtin.include_tasks: "collectd_7.yml"
  when: (ansible_facts['distribution'] == "CentOS" and ansible_facts['distribution_major_version'] == "7") or (ansible_facts['distribution'] == "RedHat" and
    ansible_facts['distribution_major_version'] == "7") or (ansible_facts['distribution'] == "OracleLinux" and ansible_facts['distribution_major_version'] ==
    "7")
  tags: collectd

- name: Collectd plugins
  ansible.builtin.include_tasks: "collectd_plugins.yml"
  when: (ansible_facts['distribution'] == "CentOS" and ansible_facts['distribution_major_version'] == "6") or (ansible_facts['distribution'] == "RedHat" and
    ansible_facts['distribution_major_version'] == "6") or (ansible_facts['distribution'] == "OracleLinux" and ansible_facts['distribution_major_version'] ==
    "6") or (ansible_distribution == "CentOS" and ansible_facts['distribution_major_version'] == "7") or (ansible_facts['distribution'] == "OracleLinux" and
    ansible_facts['distribution_major_version'] == "7") or (ansible_facts['distribution'] == "RedHat" and ansible_facts['distribution_major_version'] == "7")
  tags: collectd

- name: Collectd default plugins
  ansible.builtin.include_tasks: "collectd_default_plugins.yml"
  when: (ansible_facts['distribution'] == "CentOS" and ansible_facts['distribution_major_version'] == "6") or (ansible_facts['distribution'] == "RedHat" and
    ansible_facts['distribution_major_version'] == "6") or (ansible_facts['distribution'] == "OracleLinux" and ansible_facts['distribution_major_version'] ==
    "6") or (ansible_distribution == "CentOS" and ansible_facts['distribution_major_version'] == "7") or (ansible_facts['distribution'] == "OracleLinux" and
    ansible_facts['distribution_major_version'] == "7") or (ansible_facts['distribution'] == "RedHat" and ansible_facts['distribution_major_version'] == "7")
  tags: collectd

- name: Collectd extra plugins
  ansible.builtin.include_tasks: "collectd_extra_plugins.yml"
  when: (ansible_facts['distribution'] == "CentOS" and ansible_facts['distribution_major_version'] == "6") or (ansible_facts['distribution'] == "RedHat" and
    ansible_facts['distribution_major_version'] == "6") or (ansible_facts['distribution'] == "OracleLinux" and ansible_facts['distribution_major_version'] ==
    "6") or (ansible_distribution == "CentOS" and ansible_facts['distribution_major_version'] == "7") or (ansible_facts['distribution'] == "OracleLinux" and
    ansible_facts['distribution_major_version'] == "7") or (ansible_facts['distribution'] == "RedHat" and ansible_facts['distribution_major_version'] == "7")
  tags: collectd

# - name: restart collectd
#  ansible.builtin.service: name=collectd state=restarted
#  tags: collectd_restart
