---
# Check number of nodes to play
- name: Check if cluster consist of at least 2 nodes
  ansible.builtin.fail:
    msg: "Cluster must have at least 2 members"
  when: ansible_play_batch|count() < 2
  run_once: true
  tags: ha_cluster

# Change timezone in case if time is wrong on servers.
- name: Set timezone to Europe/Moscow
  community.general.timezone:
    name: "{{ timezone }}"
  tags: ha_cluster

- name: Include install packages
  ansible.builtin.include_tasks: "install_packages.yml"
  tags: ha_cluster

- name: Include /etc/hosts configuration
  ansible.builtin.include_tasks: "etc_hosts.yml"
  tags: ha_cluster

- name: Add firewalld rule
  become: true
  ansible.posix.firewalld:
    permanent: true
    service: high-availability
    state: enabled
  notify: Reload firewalld
  tags: ha_cluster

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
  tags: ha_cluster

- name: Include cluster status and print it
  ansible.builtin.include_tasks: "cluster_status.yml"
  tags: ha_cluster

# # Check cluster status. If cluster is working then no manipulations with cluster are allowed
# - name: Check status of cluster
#   become: true
#   ignore_errors: true
#   changed_when: false
#   ansible.builtin.command: pcs cluster status
#   register: ha_cluster_cluster_status_registered
#   tags:
#     - ha_cluster
#     - cluster_setup

# If cluster is not working, then include tasks to create cluster user, auth, setup and start cluster. Alse stonith disables and ignores quorum.
- name: Include cluster construction yml
  ansible.builtin.include_tasks: "cluster_setup.yml"
  when: (ha_cluster_cluster_status_registered.stderr.find("cluster is not currently running on this node") and (ha_cluster_cluster_status_registered is failed))
  tags:
    - ha_cluster
    - cluster_setup

- name: Include cluster status and print item
  ansible.builtin.include_tasks: "cluster_status.yml"
  tags: ha_cluster
