---
# Check number of nodes to play
- name: Check if cluster consist of at least 2 nodes
  ansible.builtin.fail:
    msg: "Cluster must have at least 2 members"
  when: ansible_play_batch|count() < 2
  run_once: true
  tags: ha_cluster

# Change timezone in case if time is wrong on servers.
- name: Set timezone to Europe/Moscow
  community.general.timezone:
    name: "{{ timezone }}"
  tags: ha_cluster

- name: Include rhel9
  ansible.builtin.include_tasks: "rhel9.yml"
  when: ((ansible_facts['distribution'] == "CentOS" and ansible_facts['distribution_major_version'] == "9") or (ansible_facts['distribution'] == "OracleLinux"
    and ansible_facts['distribution_major_version'] == "9"))
  tags: ha_cluster

- name: Include rhel7
  ansible.builtin.include_tasks: "rhel7.yml"
  when: ((ansible_facts['distribution'] == "CentOS" and ansible_facts['distribution_major_version'] == "7") or (ansible_facts['distribution'] == "OracleLinux"
    and ansible_facts['distribution_major_version'] == "7"))
  tags: ha_cluster

- name: Include rhel6
  ansible.builtin.include_tasks: "rhel6.yml"
  when: ((ansible_facts['distribution'] == "CentOS" and ansible_facts['distribution_major_version'] == "6") or (ansible_facts['distribution'] == "OracleLinux"
    and ansible_facts['distribution_major_version'] == "6"))
  tags: ha_cluster

# - name: Print output to file
#   ansible.builtin.copy:
#     content: "{{ hostvars[item] }}"
#     dest: "./{{ item }}.json"
#   delegate_to: localhost
#   with_items: "{{ ansible_play_batch }}"

# Add nodes in /etc/hosts
- name: Add hosts to /etc/hosts
  become: true
  ansible.builtin.lineinfile:
  args:
    dest: "/etc/hosts"
    regexp: "{{ hostvars[item]['ansible_default_ipv4']['address'] }}"
    line: "{{ hostvars[item]['ansible_' + cluster_interface]['ipv4']['address'] }} {{ hostvars[item]['ansible_fqdn'] }}   {{ hostvars[item]['ansible_fqdn'].split('.')[0]
      }}"
  with_items: "{{ ansible_play_batch }}"
  tags: ha_cluster

# Can use jinja2 template (works properly)
#- name: write template to /etc/hosts
#  ansible.builtin.template:
#   src: hosts.j2
#   dest: /etc/hosts
#  tags: ha_cluster

- name: Add firewalld rule
  become: true
  ansible.posix.firewalld:
    permanent: true
    service: high-availability
    state: enabled
  tags: ha_cluster

- name: Reload firewalld
  become: true
  ansible.builtin.service:
    name: firewalld
    state: reloaded
  tags: ha_cluster

# Enable pcsd
- name: Enable and start PCSD service
  become: true
  ansible.builtin.service:
    name: pcsd
    state: started
    enabled: true
  tags: ha_cluster

# Check cluster status. If cluster is working then no manipulations with cluster are allowed
- name: Check status of cluster
  ignore_errors: true
  changed_when: false
  ansible.builtin.command: pcs cluster status
  register: ha_cluster_cluster_status_registered
  tags: ha_cluster

# If cluster is not working, then include tasks to create cluster user, auth, setup and start cluster. Alse stonith disables and ignores quorum.
- name: Include cluster construction yml
  ansible.builtin.include_tasks: "cluster_setup.yml"
  when: (ha_cluster_cluster_status_registered.stderr.find("cluster is not currently running on this node") and (ha_cluster_cluster_status_registered is failed))
  tags: ha_cluster

# Enable pacemaker and corosync for CentOS-7 or OEL-7
- name: Enable cluster services on all nodes
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
    enabled: true
  with_items:
    - pacemaker
    - corosync
  when: ((ansible_facts['distribution'] == "CentOS" and ansible_facts['distribution_major_version'] == "7") or (ansible_facts['distribution'] == "OracleLinux"
    and ansible_facts['distribution_major_version'] == "7"))
  tags: ha_cluster

# Enable only pacemaker for CentOS-6 or OEL-6
- name: Enable cluster services on all nodes
  ansible.builtin.service:
    name: pacemaker
    state: started
    enabled: true
  when: ((ansible_facts['distribution'] == "CentOS" and ansible_facts['distribution_major_version'] == "6") or (ansible_facts['distribution'] == "OracleLinux"
    and ansible_facts['distribution_major_version'] == "6"))
  tags: ha_cluster

# Check cluster status
- name: Check status of cluster
  changed_when: false
  ansible.builtin.command: pcs cluster status
  register: ha_cluster_cluster_status_registered
  tags: ha_cluster

# Print cluster status
- name: Print debug messages
  changed_when: false
  ansible.builtin.debug:
    var: ha_cluster_cluster_status_registered
  tags: ha_cluster
