---
- name: Enable highavailability repo
  become: true
  ansible.builtin.command: dnf config-manager --set-enabled highavailability
  tags: ha_cluster

- name: Install all packages for CentOS-9
  become: true
  ansible.builtin.dnf:
    name: ["pacemaker", "pcs", "corosync"]
    state: present
  tags: ha_cluster
